### PR TITLE
Fix for Ruby 3.2 support

### LINKED ISSUE #640: Add Ruby 3.2 support
Ruby 3.2 is more strict on its keyword argument syntax which results in the following error.

```
ActionView::Template::Error:
       unknown keywords: method, type, attr, helper_options
```

### PR DESCRIPTION
**Pull request by rmm5t**
- Fixes module `BestInPlace::DisplayMethods::Renderer` usage for Ruby 3.2

Fixes #640

### CODE REVIEW

**Comment by adysson** [comment]
@bernat could you please accept this PR? I use best_in_place in one project and would be grateful if we could update your gem for current Ruby and Rails versions..

**Comment by mdworken** [comment]
Confirmed this PR works. Had to fork it but got it working on my fork, usable with `gem "best_in_place", git: "https://github.com/givecampus/best_in_place"`

**Comment by chaadow** [comment]
I think we should tag @seuros hopefully you can merge and release this PR 🙏🏼

**Comment by seuros** [comment]
We could release a new version. But last time I checked the code , this gem was not not thread safe .

Can someone confirm that it working correctly ?

**Comment by seuros** [comment]
Okey then. I will push a release tomorrow.

**Comment by seuros** [comment]
@chaadow you open a PR to test it against the new rubies and rails and drop support for ruby below 3.1 and rails 7.0.

This will allow having better maintenance in the future.

Thanks for the mention.

**Comment by chaadow** [comment]
Done in #644

**Pull request merged**
