### PR TITLE
Remove rails 6 deprecations

### PR DESCRIPTION
**Pull request by JDrizzy**
+ Fix rails 6 deprecations
+ Attempt to fix tests
+ Added rails 5.1 & 6 and ruby versions 2.5.7 & 2.6.5 to tests
  - Removed rails 3.2, 4.0 and 4.1

Resolves https://github.com/bernat/best_in_place/issues/623
Resolves https://github.com/bernat/best_in_place/issues/621 & https://github.com/bernat/best_in_place/issues/611

### CODE REVIEW

**Comment by dirkjonker** [comment]
@JDrizzy awesome job. I think support for Ruby 2.2 should also be dropped, as support for it has ended almost two years ago, and you have made some changes that don't work with 2.2.

**Comment by dirkjonker** [comment]
By the way, I can confirm that this works with our Rails 5.2 in production. Also works after upgrading to Rails 6 in my development environment.

**Comment by evanliewer** [comment]
Does it work with web packer?

**Comment by JDrizzy** [comment]
> Does it work with web packer?

I'm currently using it on a production app with webpacker, but the library's assets are still being provided by sprockets, unfortunately.

**Comment by Amm1r-IT** [comment]
Hi, I'm not sure how to solve the issue.
What should I do to make work with rails 6? someone gave me the link to this page but what steps should I take or follow. Any tips?

Thanks,

**Comment by JDrizzy** [comment]
@Amm1r-IT to use the changes for this PR you can either reference my repository in your gemfile:
```Ruby
gem 'best_in_place', github: 'JDrizzy/best_in_place'
```
Or, fork your own copy and reference that instead.

Ideally, this PR should be merged so you don't need to complete the above two workarounds but I'm not sure when that will be.

**Comment by Amm1r-IT** [comment]
I did gem 'best_in_place', github: 'JDrizzy/best_in_place'

There is no error in the console but  in my index view when using 

<%= best_in_place @band, :name, :as => :input %>

 I can not click to edit the text:

What am i missing in this part?

**Comment by dsounded** [comment]
What's the status ?

**Review by ArthurDatsenko — APPROVED** [review]
looks good 👍🏿

**Comment by ArthurDatsenko** [comment]
When this PR is planned to be merged?

**Pull request closed without merging**
