### PR TITLE
use css class to identify placeholder text - closes #461

### LINKED ISSUE #461: Placeholder element class for style
It would be really great to be able to style the span tags based on if the span was built and contains the placeholder text or not. Maybe something like `bip-placeholder`.

My idea is to be able to style placeholders as grey text.

Would that be something you would be willing to add or accept a PR?

### PR DESCRIPTION
**Pull request by soberstadt**

### CODE REVIEW

**Comment by vanboom** [comment]
:+1:

**Comment by soberstadt** [comment]
@vanboom, glad to hear it helped!

**Comment by joallard** [comment]
I would have named the additional class `placeholder`, since we already know with class `best_in_place` what it is. Otherwise, +1 please merge

**Comment by soberstadt** [comment]
Sweet, thanks!

**Pull request merged**
