### PR TITLE
Make popup with validation errors working in IE8

### PR DESCRIPTION
**Pull request by Hirurg103**
Seems that class is a reserved word in IE8, so wrap it in quotes

### CODE REVIEW

**Comment by Hirurg103** [comment]
Seems this is duplicate of #484. Why it isn't merged?

**Comment by Hirurg103** [comment]
See also [this stackoverflow post](http://stackoverflow.com/questions/9480592/jquery-setting-attr-ie8-error) related to issue

**Comment by seuros** [comment]
Well probably because we should not be using IE8 at first place.

**Comment by Hirurg103** [comment]
@seuros Totally agree

**Pull request closed without merging**
